import image1 from "@/assets/images/ideapad-gaming-3i-01-500x500 1.png";
import image2 from "@/assets/images/ak-900-01-500x500 1.png";
import image3 from "@/assets/images/547953_9C2ST_8746_001_082_0000_Light-Gucci-Savoy-medium-duffle-bag 1.png";
import image4 from "@/assets/images/Copa_Sense 1.png";
import image5 from "@/assets/images/New-Mercedes-Benz-Gtr-Licensed-Ride-on-Car-Kids-Electric-Toy-Car 1.png";
import image6 from "@/assets/images/jacket.png";
import image7 from "@/assets/images/image 63.png";
import { TProducts } from "../../types";

export const PRODUCTS: TProducts[] = [
  {
    id: "1",
    name: "Ideapad gaming-3i-01-500x500",
    off_price: 430,
    price: 180,
    promo: true,
    category: "Computer",
    image: image1,
    rating: 3.5,
  },
  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    price: 970,
    promo: false,
    category: "Accessories",
    image: image2,
    rating: 5,
  },
  {
    id: "3",
    name: "Gucci duffle bag",
    price: 120,
    promo: true,
    off_price: 250,
    category: "Fashion",
    image: image3,
    rating: 4.5,
  },
  {
    id: "4",
    name: "Jr. Zoom Soccer Cleats",
    price: 970,
    promo: false,
    category: "Sports",
    image: image4,
    rating: 5,
  },
  {
    id: "5",
    name: "Mercedes-Benz-Gtr",
    price: 120,
    off_price: 210,
    promo: true,
    category: "Vehicle",
    image: image5,
    rating: 2.5,
  },
  {
    id: "6",
    name: "Jacket",
    price: 970,
    promo: false,
    category: "Fashion",
    image: image6,
    rating: 5,
  },
  {
    id: "7",
    name: "Ideapad gaming-3i-01-500x500",
    off_price: 430,
    price: 180,
    promo: true,
    category: "Computer",
    image: image1,
    rating: 3.5,
  },
  {
    id: "8",
    name: "AK-900 Wired Keyboard",
    price: 970,
    promo: false,
    category: "Accessories",
    image: image2,
    rating: 5,
  },
  {
    id: "9",
    name: "Gucci duffle bag",
    price: 120,
    promo: true,
    off_price: 250,
    category: "Fashion",
    image: image3,
    rating: 4.5,
  },
  {
    id: "10",
    name: "Jr. Zoom Soccer Cleats",
    price: 970,
    promo: false,
    category: "Sports",
    image: image4,
    rating: 5,
  },
  {
    id: "11",
    name: "Mercedes-Benz-Gtr",
    price: 120,
    off_price: 210,
    promo: true,
    category: "Vehicle",
    image: image5,
    rating: 2.5,
  },
  {
    id: "12",
    name: "Jacket",
    price: 970,
    promo: false,
    category: "Fashion",
    image: image6,
    rating: 5,
  },
  {
    id: "13",
    name: "HAVIT HV-G92 Gamepad",
    price: 650,
    promo: false,
    category: "Accessories",
    image: image7,
    rating: 5,
  },
];
